[package]
name = "wspr"
version = "0.1.0"
authors = ["Jeff Hlywa <jhlywa@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"


[features]
defmt-03 = ["dep:defmt"]

[dependencies]
defmt = { version = "0.3", optional = true }
